# Generated by Django 6.1.1 on 2026-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('soloTask', models.BooleanField()),
                ('taskLocation', models.CharField(max_length=300)),
                ('taskDate', models.DateField()),
            ],
        ),
    ]
