# Generated by Django 6.1.1 on 2026-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentation', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskPurpose',
            field=models.TextField(null=True),
        ),
    ]
