# Generated by Django 6.1.1 on 2026-09-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentation', '0003_task_taskpurpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskPurpose',
        ),
    ]
